name: second

on: 
  push:
  workflow_dispatch:

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: date +"%D %T"

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: "Write-Output $(Get-Date)"
  
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: date +"%D %T"

  job4: 
    name: Four job
    runs-on: macos-latest
    needs: [job1, job2, job3]
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: date +"%D %T"
